### ISSUE TITLE
Issue with the rss reader

### ISSUE THREAD

**Issue by ckipp01** [ckipp01/webring-checker#2]
content.map is not a function

**Comment by davidag** [comment]
I was going to report this :relaxed: 

I'm working on a [pelican](https://docs.getpelican.com/en/latest/index.html) webring plugin and I was looking into this API to find out if I could get the latest posts from the xxiivv webring.

Great work!

**Comment by ckipp01** [comment]
Ha, yes I just realized it wasn't working with the latest feed that was added into the webring. I started a new job today so it may be a bit before I get it fixed!

**Comment by ckipp01** [comment]
Recent push fixes this.
