### ISSUE TITLE
parser broke due to recent changes to sites.js

### ISSUE THREAD

**Issue by ghost** [ckipp01/webring-checker#3]
i think https://github.com/XXIIVV/Webring/issues/306 should be addressed first,
since parser would not be needed with simple json file

**Comment by ckipp01** [comment]
Just pushed up changes to fix this.

**Comment by ghost** [comment]
i think it broke again
> Unexpected token l in JSON at position 98

**Comment by ckipp01** [comment]
Ugh, I really wish this was just json.

**Comment by ghost** [comment]
how long until you giveup and just use full AST parser 😂
